name = "fasttmle"

[install]
completion = true
quiet = false
optimize = 2

[sysimg]
incremental=true
filter_stdlibs=false

[sysimg.precompile]
execution_file = ["deps/execute.jl"]

[application]
incremental=true
filter_stdlibs=false

[application.precompile]
execution_file = ["deps/execute.jl"]